### ISSUE TITLE
Review 11.10

### ISSUE THREAD

**Issue by YiNNx** [Gresham429/dynamic_heart_detection#1]
https://github.com/Gresham429/dynamic_heart_detection/blob/20f45946183651436dfb4073a53ca030bca7dbd4/router/protect.go#L10-L13

RESTful API 记得改

https://github.com/Gresham429/dynamic_heart_detection/blob/20f45946183651436dfb4073a53ca030bca7dbd4/config/config.go#L31-L32

最好是养成处理好每个 err 的习惯，像 json 解析这种操作很容易抛出异常的，不打日志甚至根本不处理的话对代码调试和服务稳定性都不利

--- 

话说真的重构完了吗，怎么感觉 Controller 里面好多之前提过的问题都没改

**Comment by Gresham429** [comment]
没有重构完，现在刚改完昨天朱学长给的review

**Comment by Gresham429** [comment]
只差API文档了
